package com.vaadin.miner;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

public class MainWindow extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout fieldLayout;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button btn_adv;
	@AutoGenerated
	private Button button_Med;
	@AutoGenerated
	private Button btn_Beginer;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainWindow() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		btn_Beginer.addClickListener(new Button.ClickListener() {		
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				Game.getInstance().startGame(10, 10, fieldLayout);
			}
		});
		button_Med.addClickListener(new Button.ClickListener() {			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				Game.getInstance().startGame(16, 40, fieldLayout);
			}
		});
		btn_adv.addClickListener(new Button.ClickListener() {			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				Game.getInstance().startGame(25, 100, fieldLayout);
			}
		});
	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("790px");
		verticalLayout_2.setHeight("580px");
		verticalLayout_2.setMargin(false);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_2.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalLayout_2.addComponent(horizontalLayout_2);
		
		// fieldLayout
		fieldLayout = new HorizontalLayout();
		fieldLayout.setImmediate(false);
		fieldLayout.setWidth("680px");
		fieldLayout.setHeight("346px");
		fieldLayout.setMargin(false);
		verticalLayout_2.addComponent(fieldLayout);
		
		return verticalLayout_2;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("680px");
		horizontalLayout_1.setHeight("60px");
		horizontalLayout_1.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Label");
		horizontalLayout_1.addComponent(label_1);
		horizontalLayout_1.setComponentAlignment(label_1, new Alignment(48));
		
		return horizontalLayout_1;
	}


	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("780px");
		horizontalLayout_2.setHeight("73px");
		horizontalLayout_2.setMargin(false);
		
		// btn_Beginer
		btn_Beginer = new Button();
		btn_Beginer.setCaption("Beginer");
		btn_Beginer.setImmediate(true);
		btn_Beginer.setWidth("-1px");
		btn_Beginer.setHeight("-1px");
		horizontalLayout_2.addComponent(btn_Beginer);
		horizontalLayout_2
				.setComponentAlignment(btn_Beginer, new Alignment(48));
		
		// button_Med
		button_Med = new Button();
		button_Med.setCaption("Intermediate");
		button_Med.setImmediate(true);
		button_Med.setWidth("-1px");
		button_Med.setHeight("-1px");
		horizontalLayout_2.addComponent(button_Med);
		horizontalLayout_2.setComponentAlignment(button_Med, new Alignment(48));
		
		// btn_adv
		btn_adv = new Button();
		btn_adv.setCaption("Advanced");
		btn_adv.setImmediate(true);
		btn_adv.setWidth("-1px");
		btn_adv.setHeight("-1px");
		horizontalLayout_2.addComponent(btn_adv);
		horizontalLayout_2.setComponentAlignment(btn_adv, new Alignment(48));
		
		return horizontalLayout_2;
	}
}
